//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDMTestJob.Domian.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Number { get; set; }
        public Nullable<int> Amount { get; set; }
        public string DueTime { get; set; }
        public string Description { get; set; }
    }
}
